const COMMUNICATION_TYPES = Object.freeze({

    INVITATION: "INVITATION",

    PASSWORD_RESET: "PASSWORD_RESET",

    RESERVATION_CONFIRMATION: "RESERVATION_CONFIRMATION",

    RESERVATION_REMINDER: "RESERVATION_REMINDER",

    RESERVATION_CANCELLED: "RESERVATION_CANCELLED",

    DRIVER_ASSIGNED: "DRIVER_ASSIGNED",

    PAYMENT_RECEIVED: "PAYMENT_RECEIVED",

    PAYMENT_FAILED: "PAYMENT_FAILED",

    INVOICE: "INVOICE",

    QUOTE: "QUOTE",

    CONTACT_FORM: "CONTACT_FORM",

    CUSTOM: "CUSTOM"

});

module.exports = COMMUNICATION_TYPES;